### ISSUE TITLE
When rebuilding a project, browser window shows Cannot GET /

### ISSUE THREAD

**Issue by adambuczynski** [johnpapa/lite-server#10]
I assume this has to do with the fact that my build process removes the destination directory before building, which is the directory lite-server is watching. Then, it displays `Cannot GET /` on the browser window and doesn't refresh anymore after the build is complete.

Is there anything that can be done about this?

**Comment by johnpapa** [comment]
its best to serve from the source folder with lite-server. its for dev only

**Comment by adambuczynski** [comment]
It's a dev build...
