### ISSUE TITLE
Can lite-server configuration support non-standard application structures?

### ISSUE THREAD

**Issue by robmarston** [johnpapa/lite-server#102]
This is more of a capabilities question then an issue report, apologies -- I wasn't sure where else to ask.  My Angular 2 application's structure is as follows (redacted for readability):

```
- node_modules
  - somescript.js 
- src
  - index.html
- bs-config.json
```

In my bs-config file I have `server.baseDir` set to `./src`. This is working. That said, index.html includes scripts in the node_modules directory which are inaccessible due to the `baseDir` setting. My question is, if I set `baseDir` to `./` can I specify where the server looks for the index file or should I just not use lite-server and use a standard full-featured server in stead?

Thanks all!

**Comment by maciej-gurban** [comment]
Instead of including files from node_modules in your index.html directly, you could include them in one JS file using browserify's require() or ES6 import syntax. This will bundle all imported/required scripts into your that one JS file. There's more ways to do that, but this might be the simplest.

**Comment by robmarston** [comment]
@maciej-gurban I don't think ES6's import syntax will work because the node_modules directory is outside the base directory but you may be on to something with the browserify suggestion. I'm already using system.js so there's probably something I could do there as well. Thank you!

**Comment by maciej-gurban** [comment]
You're most likely importing NPM modules by doing something like `<script src="node_modules/foo/foo.js"></script>`. Is that so?

Nearly all libraries published on NPM can be included using require() or import syntax by specifying their name only - `require('foo')` or `import myFoo from 'foo'`. This will take contents of specified library and include them in the file that has the import/require statement.

You don't specify any file paths, just the name of a dependency, so you can include a library (or one of its functions) at any level of nesting if your directory structure. The rest will be taken care of.
