### ISSUE TITLE
create proxy to outside server

### ISSUE THREAD

**Issue by moshmage** [johnpapa/lite-server#108]
Before you open an issue, please check if a similar issue already exists or has been closed before.

### A descriptive title
The connection to be proxied

### Bug repro steps
- clone angular2 quickstart
- change bs-conf.json to bs-conf.js
- change the package.json

add this to bs-confg
```js
var proxy = require('http-proxy-middleware');
var fallback = require('connect-history-api-fallback');
module.exports = {
  browser: ['chrome'],
  server: {
    middleware: {
      1: proxy('/twitter', {target: 'https://api.twitter.com', changeOrigin: true }),
      2: fallback({index: '/index.html', verbose: true})
    }
  }
};
```
make a call to /twitter/foo/bar/, get or post, and you'll get 
```logtalk
[1] [HPM] Error occurred while trying to proxy request /twitter/oauth2/token from localhost:3000 to https://api.twitter.com (undefined) (https://nodejs.org/api/errors.html#errors_common_system_errors)
[1] 16.11.07 16:44:12 500 POST /twitter/oauth2/token
```
### Environment
"lite-server": "^2.2.2",

**Comment by moshmage** [comment]
yeah.. nevermind *facepalm*

**Comment by JJBocanegra** [comment]
But how did you solve it?
