### ISSUE TITLE
Redirect-loop to root

### ISSUE THREAD

**Issue by matthiasbruch** [johnpapa/lite-server#11]
From the angular tutorial, I was told to use "npm start" which runs:

concurrent "npm run tsc:w" "npm run lite" 

if I move the content of my app into a subfolder and redirect there, I'm getting into a loop. Somehow the file index-file from the root folder is delivered at the app-subfolder as well. I thought I misconfigured something, but another http-server (serve) doesn't do that and brings me straight into the app.

Am I missing something? I saw that you can pass the subfolder to serve, but I need some files at the root, so this is not an option.

Thanks.

**Comment by cgmartin** [comment]
Hi @matthiasbruch, in the new 2.x version of lite server you can configure the base directory of your app  by creating a `bs-config.json` file in your project:
```json
{
  "files": ["./app/**/*.{html,htm,css,js}"],
  "server": { "baseDir": "./app" }
}
```

**Comment by cgmartin** [comment]
...and you can update your local tutorial project with the new `2.0.1` version by doing:
```
$ npm install --save-dev lite-server@latest
```

**Comment by johnpapa** [comment]
with v2 you are set.
