### ISSUE TITLE
run a custom script when change occur

### ISSUE THREAD

**Issue by yanai101** [johnpapa/lite-server#111]
first - john - i'm a big fan... -great job
q:
if i want to run a script when change occur - how i can do that

**Comment by johnpapa** [comment]
thanks

that would not be something for lite-server.

you could do more with gulp or webpack for this

**Comment by bsc1780** [comment]
Hello John I have a offer by Google and one more to make a project I DoD
one I need three engineers. I would love for you to be in on this. It's
gonna be big.
