### ISSUE TITLE
Stop Running Query Lite server

### ISSUE THREAD

**Issue by DivWork** [johnpapa/lite-server#113]
hello
I am using lite server for a new angular 2 desktop app
I have settled the environment correctly and everything is working fine. but i am not to stop a running npm start . If you can tell me how to do that.
Thank you,

**Comment by Maverick4u** [comment]
CTRL+C

**Comment by SanthoshBabuMR** [comment]
how do we stop lite server using npm scripts?
{
"stop": "lite-server --stop"
}
