### ISSUE TITLE
localonly configuration

### ISSUE THREAD

**Issue by andrewkoltsov** [johnpapa/lite-server#114]
How I can pass localOnly (https://www.browsersync.io/docs/options/#option-localOnly) parameter to  lite-server to browsersync?

**Comment by tomekr** [comment]
I couldn't get the `localOnly` configuration option to pass thru. However, I achieved the same by setting host to `127.0.0.1`. So in my root, I have a `bs-config.json` file with the following contents:

~~~json
{
  "ui": false,
  "host": "127.0.0.1"
}
~~~

**Comment by tomekr** [comment]
Scratch that, even though the output from the command line show's it's using 127.0.0.1:

![http://i.imgur.com/udYOGbt.png](http://i.imgur.com/udYOGbt.png)

 it's not actually using that and it's still listening on all interfaces:

![netstat](http://i.imgur.com/A2pwSdf.png)

that's unfortunate and looks like it's a bug

**Comment by johnpapa** [comment]
that would be a browser sync question
