### ISSUE TITLE
Quotes around parameters not working on Windows

### ISSUE THREAD

**Issue by adambuczynski** [johnpapa/lite-server#12]
My partner has to work on a Windows environment, and was having trouble to start up the lite server. There were no errors in the console, but the only thing displayed in the browser was `Cannot GET /`.

```shell
lite-server --port 8080 --baseDir './dist/dev' --files './dist/dev/**/*'
```

**Comment by adambuczynski** [comment]
Update: even when not specifying any baseDir or files, and placing the index.html in the project root, we still get the same result

**Comment by adambuczynski** [comment]
With verbose mode on, it can be seen that the baseDir is incorrectly set as:

`baseDir: '\'./dist/dev\''

So it seems to be escaping the `'` character on windows. This does not happen on OS X. Is this a windows specific issue or something lite-server is doing?

**Comment by johnpapa** [comment]
Version 2.0 has been published. New API that follows the exact `bs-config.js` format for all overrides.
