### ISSUE TITLE
Get rid of the Unknowns

### ISSUE THREAD

**Issue by adambuczynski** [johnpapa/lite-server#13]
When running lite-server, I always see a lot of angry red `Unknown`s, which makes me think errors are happening while they are not:

![ss](https://www.dropbox.com/s/434zdtmx6fw81fx/Screenshot%202016-01-13%2008.59.07.png?dl=1)

Any way to get rid of those, or at least change the color to something less error-like?

**Comment by johnpapa** [comment]
not sure. we may swap out browser sync as i am not sure if tsc and bs are clashing too with the file watchers

**Comment by cgmartin** [comment]
Addressed in #16, closing

**Comment by adambuczynski** [comment]
This was actually not a BrowserSync issue, but comes from the `connect-logger`'s default log format. I've removed the route form it which fixed it.
