### ISSUE TITLE
[QUESTION] How can I replace index.html to index.php as index of the site?

### ISSUE THREAD

**Issue by smplyjr** [johnpapa/lite-server#130]
I have bs-config.json on my project root and it contains this
```json
{
  "files": [
    "./*.{html,htm,css,js,php}"
  ]
}
```

and on my package.json I added this line "lite-server bs-config.json", It seems that it didn't work. Where am I wrong?

Note: it reloads the page when I changed a code on one of my php file but its the index.html is the one I wanted to change in index.php

Sorry for my bad english.

**Comment by zatchgordon** [comment]
Sounds like you might be looking for a different server.
[https://www.npmjs.com/package/node-php-server](node-http-server)looks like a server that was made for running php files

**Comment by smplyjr** [comment]
+1 Thanks for the info.
