### ISSUE TITLE
Error using lite-server for create-react-app

### ISSUE THREAD

**Issue by gersondi** [johnpapa/lite-server#191]
Trying to use lite-server instead of `npm start` in create-react-app. But i run into the following error Cannot GET / on browser

### Steps to reproduce
```npx create-react-app amplify-react-app```
``` cd amplify-react-app```
``` npm install lite-server --save-dev```
``` npm run dev```

### Environment
- `lite-server` version: 2.6.1
- `nodejs` version: 12.16.1.
- `npm` version: 6.13.4 
- OS type/version: windows10
- Browser: Chrome
![image](https://user-images.githubusercontent.com/55311391/103689619-973f8a80-4fb9-11eb-8ccd-4075be01998f.png)

Contents of package.json
```
{
  "name": "amplify-react-app",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@aws-amplify/ui-react": "^0.2.33",
    "@testing-library/jest-dom": "^5.11.8",
    "@testing-library/react": "^11.2.2",
    "@testing-library/user-event": "^12.6.0",
    "aws-amplify": "^3.3.13",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-scripts": "4.0.1",
    "web-vitals": "^0.2.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "dev": "lite-server",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "lite-server": "^2.6.1"
  }
}

```

**Comment by misoronfox** [comment]
did you find a solution?

**Comment by gersondi** [comment]
@misoronfox I was using AWS Educate account maybe that caused the issue. 
As far as the solution is concerned I didn't move on with this AWS service hence didn't look into this any more.

**Comment by Debarna-Datta** [comment]
hello im getting  the same error...please help
