### ISSUE TITLE
Expose BrowserSync or Create custom script

### ISSUE THREAD

**Issue by johnpapa** [johnpapa/lite-server#22]
Let's track our ideas in an issue and propose either a way to expose BS entirely or use a fully custom script that deprecates lite-server.

Goals:
- a quick/fast server 
- serves static assets
- handle fallback routes for SPAs
- exposes all browser-sync features (dont recreate the wheel)
- doesn't collide with simultaneous watchers from transpilers like TypeScript or babel
- minimalistic (run via NPM script)

The biggest advantage to having an npm package is that we can `npm install lite-server` and we have it. if we go the route of having a script and deprecate lite-server, we need to `npm install` both the fallback package and browsersync + have a short script that runs them together. This is the crux of it.

cc / @cgmartin

**Comment by cgmartin** [comment]
Sounds like the primary use case is keeping the [NG2 quickstart instructions](https://angular.io/docs/ts/latest/quickstart.html) simple. 

Using a custom browser sync config file that replaces lite-server would require changing the quickstart documentation, adding a file to copy/paste in addition to the `package.json` that is already required. ie.
```
var historyFallback = require('connect-history-api-fallback');
var log = require('connect-logger');
/*
 | For up-to-date information about the options:
 |   http://www.browsersync.io/docs/options/
 */
module.exports = {
    "files": [
      './**/*.html', './**/*.css', './**/*.js'
    ],
    "server": {
      "baseDir": './',
      "middleware": [
        log(),
        historyFallback({"index": '/index.html'})
      ]
    },
    "port": 3000
};
```

Both methods are able to satisfy the goals you mention as it exists today, more or less. A benefit of `lite-server` is that you have control/flexibility over any future changes to the quickstart server (for any functionaly outside of what browsersync may provide) without requiring changes to the quickstart documentation. And if the crux of matter is simple instructions, I think the `lite-server` npm package is the way to go.

**Comment by johnpapa** [comment]
If we go the route of `lite-server`, then we need to expose everything for browser sync and not override it. Plus we'd also need the `index.html` and port to be flexible. The port should already be in the bs json.

Want to take a stab at a sample for it?

**Comment by cgmartin** [comment]
The PR #16 already exposes everything via a separate (optional) `bs-config.json` file. As far as duplicating all of browsersync's command line arguments, I'm not in favor. :) Too painful to maintain and keep in sync.

**Comment by johnpapa** [comment]
I meant that the json file allows all bs properties, but we are setting the port ourselves. so we want to use the bs file instead.

and we should add a `fallback` file property for cases where folks want something other than the index.html.

**Comment by cgmartin** [comment]
OK, thanks, I think I follow - I'll make modifications to PR #16 and we'll go from there :)

**Comment by johnpapa** [comment]
coolio!

**Comment by johnpapa** [comment]
@cgmartin you may want to add `verbose` too (see https://github.com/johnpapa/lite-server/pull/24/files)

**Comment by cgmartin** [comment]
Updated PR #16 based on the feedback here. Let me know if this jives with what you're looking for.

**Comment by johnpapa** [comment]
Version 2.0 has been published. New API that follows the exact `bs-config.js` format for all overrides.
