### ISSUE TITLE
--files does not work

### ISSUE THREAD

**Issue by martinoppitz** [johnpapa/lite-server#23]
Try `--files '/**/*.html'`

**Comment by johnpapa** [comment]
Version 2.0 has been published. New API that follows the exact `bs-config.js` format for all overrides.

**Comment by JJBocanegra** [comment]
So now this is the only way to change the index file?

```
module.exports = {
  server: {
    middleware: {
      // overrides the second middleware default with new settings
      1: require('connect-history-api-fallback')({index: '/index.html', verbose: true})
    }
  }
};
```

and installing another dependency?

Isn't it better to try to keep it simple without another dependencies?
