### ISSUE TITLE
Fresh install of lite-server using KoaJS

### ISSUE THREAD

**Issue by Gacnt** [johnpapa/lite-server#33]
I've used KoaGenerator to generate a skeleton app for me.

I've installed lite-server.

```
    "scripts": {
        "c": "babel -d app/ src",
        "tsc": "tsc",
        "tsc:w": "tsc -w",
        "lite": "lite-server --browser chrome --open local",
        "dev": "npm run c && concurrent \"npm run tsc:w\" \"npm run lite\" ",
        "start": "npm run c && ./node_modules/.bin/nodemon app/bin/www"
    },
```

I currently have this, when I run `npm run dev` everything runs, but all my routes 404. Any idea where I should look into fixing this? Do I need to already start my server, then run lite-server after? Any information would be great thanks.

**Comment by johnpapa** [comment]
lite server options changed with v2. It needs a bs config file. check the readme
