### ISSUE TITLE
Installing lite-server error Can't find python executable

### ISSUE THREAD

**Issue by pthalacker** [johnpapa/lite-server#34]
I am unable to install lite-server.  I get an error that node-gyp can't find the python executable.  The only solution I find online is to install python and C++ and Windows SDK and build it from scratch.  Am I missing something?

**Comment by billfranklin** [comment]
I too am having that error appear during the install

**Comment by johnpapa** [comment]
probably a problem with installing other node modules too, right? we need more info to know what the issue is

**Comment by pthalacker** [comment]
Nope.  lite-server is the only module I have ever had this problem with.  I switched to http-server to avoid the problem,

**Comment by johnpapa** [comment]
If you have more info, we can look into it.

**Comment by pthalacker** [comment]
When I get a chance I will re run it and upload the error output

**Comment by jjhampton** [comment]
I don't think this is an issue specifically w/ Lite Server, but is related to an issue that an issue that node-gyp has on Windows - apparently it is one of Browser-sync's dependencies.

See this (long) thread for a solution - you may have to install the C++ build tools and Python 2.7 as I did.

**Comment by johnpapa** [comment]
seems that is the case. closing
