### ISSUE TITLE
browser-sync version in package json needs to be higher to avoid CPU running at 100% 

### ISSUE THREAD

**Issue by softchris** [johnpapa/lite-server#36]
Update browser-sync version in package json to at least browser-sync@2.2.3  to avoid CPU bug... As angular.io depends on this package this is a low hanging fruit that would make people more positive towards angular2

**Comment by johnpapa** [comment]
we are at `^2.11.1` ... which is great than 2.2.3. what are you suggesting we do?

**Comment by dizabl** [comment]
Hmm so problem is angular.io really. Cpu runs wild on windows when trying out npm start. ( after having done npm install). Problem seems to go away after removing and readding browser sync..  You are right on version number though..  I thought it was related to this project

**Comment by dizabl** [comment]
I think you can close this issue.. Seems like browser sync + sublime build < 3083 causes your cpu to run wild due to a corrupt index. So sublime at fault but just upgrade it to latest fixes it

**Comment by johnpapa** [comment]
ok
