### ISSUE TITLE
404 index.html

### ISSUE THREAD

**Issue by winnemucca** [johnpapa/lite-server#37]
I have added folders to my structure going from app => index.html  to src => client => app=> index.html.  Now all of a sudden I am getting a 404 when I run my script.  Example of my package.json below 

```json
{
  "name": "haComponentsPage",
  "version": "1.0.0",
  "description": "",
  "main": "",
  "scripts": {
    "start": "lite-server"},
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@angular/router": "^0.1.0",
    "angular": "1.5.0",
    "bootstrap": "^3.3.6"
  },
  "devDependencies": {
    "lite-server": "^2.0.1"
  }

}

```

*** note I am changing the structure from this repository.https://github.com/petebacondarwin/ng1-component-router-demo
 For the new component router

**Comment by GooSP** [comment]
You should probably add a "bs-config.json" file in your project root directory and specify where the server needs to serve file from.

```
{
  "server": { "baseDir": "./src/client/app" }
}
```

**Comment by winnemucca** [comment]
Great thanks

**Comment by nileshsahitya9** [comment]
- 
![screenshot 1](https://user-images.githubusercontent.com/36760635/45948858-489f9980-c017-11e8-958d-9ec862dde8d1.png)
i am getting error cannot get/ at 3000 localhost

**Comment by nileshsahitya9** [comment]
> You should probably add a "bs-config.json" file in your project root directory and specify where the server needs to serve file from.
> 
> ```
> {
>   "server": { "baseDir": "./src/client/app" }
> }
> ```

hey i didn't get it, what to do?
