### ISSUE TITLE
Errors Installing

### ISSUE THREAD

**Issue by billfranklin** [johnpapa/lite-server#39]
I have Python2.7.11 for Windows x86/x64 installed on Windows 7 x64.  When I run npm install lite-server --save-dev, I get the following errors:
TypeError: Request path contains unescaped characters.

And a few 404 status codes downloading 32-bit node.libs.

**Comment by johnpapa** [comment]
anyone else on windows able to test this?

**Comment by johnpapa** [comment]
moving to https://github.com/johnpapa/lite-server/issues/54
