### ISSUE TITLE
lite-server & gulp

### ISSUE THREAD

**Issue by kkasaei** [johnpapa/lite-server#40]
Hi John,

What is your suggestion for using lite-server with Gulp,
can you please provide me with and example?

**Comment by mikeerickson** [comment]
@kkasaei Why do you need gulp interaction?  lite-server is a simple webserver that you start and it does its thing.  

[More information here](https://github.com/johnpapa/lite-server/issues/31)

**Comment by kkasaei** [comment]
@mikeerickson , My concerns is about testing. so lets say with browser-sync and gulp you define a test  like this:

gulp.task('serve-specs', function() {
    browserSync.init({
        notify: false,
        port: 8081,
        server: {
            baseDir: ["test", "app"],
            routes: {
                '/bower_components': 'bower_components'
            }
        }
    });

    gulp.watch(['app/**/*.*'])
        .on('change', browserSync.reload);
});


so how should i approach the same thing with lite-server?

cheers

**Comment by cgmartin** [comment]
@kkasaei just use [browsersync directly with gulp](https://www.browsersync.io/docs/gulp/). `lite-server` is a small configuration wrapper around `browsersync` and isn't meant for gulp integration. Copy [lite-server's configuration](https://github.com/johnpapa/lite-server/blob/master/lib/config-defaults.js#L8-L16) and use with your browsersync config in your custom gulp file.

**Comment by kkasaei** [comment]
@cgmartin Thanks. I'll check it and get back to you.

**Comment by nelsonomuto** [comment]
we would use gulp to transpile our less files for example

**Comment by johnpapa** [comment]
lite-server is meant to get you started. it helps those who want to write angular and not worry about a node server, until they have time to create the server they want. node, asp.net, java, whatever.

once you decide to write server code, it is time to put lite-server aside and use a real server.

**Comment by nelsonomuto** [comment]
you can still easily integrate gulp with lite-server and leverage less by having a gulp watch on the css file @johnpapa. This way you can take advantage of the browser-sync you get out of the box with lite server.

Just thought it would be worth it to call out, it only added 3 lines of code to my gulpfile to execute lite server as a child process.

Here is my [gulpfile](https://gist.github.com/nelsonomuto/08c139d86ffa1e7a08333b1f5f1f740d)

Good job by the way, lite server is a great tool.

**Comment by nelsonomuto** [comment]
@kkasaei here is an example of using gulp and lite server for your reference: https://github.com/nelsonomuto/lite-server-gulp

**Comment by cgmartin** [comment]
@nelsonomuto fyi, a recent change in lite-server `2.2.0` now allows you to `require('lite-server');` from your gulpfile and use its API instead of having to go through `exec`. This offers some additional flexibility for those who might want to get a reference to browsersync itself from lite-server (additional watchers, events, etc.) or need to wait on when browsersync has started via a callback.

https://github.com/johnpapa/lite-server/blob/master/package.json#L5
https://github.com/johnpapa/lite-server/blob/master/index.js

**Comment by johnpapa** [comment]
good point @nelsonomuto :)

**Comment by t3dodson** [comment]
@cgmartin Is there any docs available on how one would start to integrate gulp with lite-server?

**Comment by MarkusTischendorf** [comment]
@t3dodson I was able to start the lite-server from my gulpscript as follows:
```javascript
const gulp = require("gulp");
const lite = require("lite-server");

const BS_CONFIG_FILE = "config/lite-server/bs-config.json";

gulp.task("start:dev:serve", () => {
    lite.server({ argv: ["", "", "-c", BS_CONFIG_FILE]}, () =>
    {
        console.log("Lite-server running..")
    });
});
```
Defining the argv property is not very nice. I'm not sure if there is a better opportunity.
