### ISSUE TITLE
Respect shell colors

### ISSUE THREAD

**Issue by atrefz** [johnpapa/lite-server#44]
You use connect-logger, which is using hard coded color values to do logging of files, but not hardcoded background colors, which results in conflicts with often used themes, such as solarized (i cant read the filename of a watched file, since it has the same color as the background).

It would be great it you could either:
- provide an option to turn colors off
- set the background as well(worst option, but better than nothing)
- respect the shells colors and use the default foreground color, instead of hardcoding a black.

**Comment by johnpapa** [comment]
We dont change anything, we use BrowserSync and connect logger. This is a dev server, and we're not going to be adding any features beyond the core we have.

**Comment by atrefz** [comment]
Yes, its a dev server, with logs that cant be read by lots of shell users. Great job.

**Comment by johnpapa** [comment]
Themes run into this all the time. Feel free to make a PR on Browser Sync and or the connect logger to change this. Lite-server is a pass through for these.

Thanks, Chris and I appreciate that you think we did a "great job". ALways nice when the community is helpful and appreciative!
