### ISSUE TITLE
lite-server & req.cookies

### ISSUE THREAD

**Issue by pierreclr** [johnpapa/lite-server#45]
Hi,

I actually want to use lite-server for my angular2 app development but I need to have localhost cookies ressources passed through req.cookies for each call from service to backend. (to handle user auth) If I use my node server instead of lite-server everything is working but I can't refresh angular routes without haing "cannot get" that's why I want to use lite-server ! Does anyone has an idea of how can I fix my problem ?

Thank you

**Comment by johnpapa** [comment]
we support what BrowserSync supports. check there.
