### ISSUE TITLE
enable bs-config.json comments

### ISSUE THREAD

**Issue by myusrn** [johnpapa/lite-server#46]
currently tsconfig.json, typings.json and .vscode/launch.json + settings.json + tasks.json all support use of // and /* */ comments to store details of alternative settings and notes relating to contents of those files.

i tried doing this in lite-server dependent bs-config.json, e.g. as in following example, and this breaks 'npm run lite-server' support.
```
{ 
  "port": 3000,  // == default and for specific port use "port": 8080 or "https": true, "port": 44300,
  //"files": ["./src/**/*.{html,htm,css,js}"],
  "files": ["./**/*.{html,htm,css,js}"],
  //"server": { "baseDir": "./src" }
  "server": { "baseDir": "./" }
}

```
is enabling similar support in lite-server dependent bs-config.json file something that is in the plans already?  

would it be change that has to happen in the https://github.com/johnpapa/lite-server or https://github.com/browsersync/browser-sync package release work?

**Comment by johnpapa** [comment]
no plans for it. we support what BS supports.
