### ISSUE TITLE
Update engine.io-client dependency to avoid xmlhttprequest dependency which does not work behind corporate proxy

### ISSUE THREAD

**Issue by ederkley** [johnpapa/lite-server#47]
The current dependency for lite-server is to use engine.io-client@1.5.4 which has a sub-dependency of xmlhttprequest and this module has a known issue for users behind corporate firewall/web-proxy as it apparently ignores the https-proxy config item and tries to connect directly to github.com leading to timeouts:
> npm ERR! fetch failed https://github.com/rase-/node-XMLHttpRequest/archive/a6b6f2.tar.gz
> npm WARN retry will retry, error on last attempt: Error: tunneling socket could not be established, cause=socket hang up

engine.io-client was updated at end of January 2016 to use xmlhttprequest-ssl dependency instead and fixes the above issue.  
Currently engine.io-client v1.6.8 installs properly from behind our corporate firewall and web-proxy.

Hopefully lite-server can be updated to use the newer engine.io-client

**Comment by cgmartin** [comment]
lite-server depends on browserSync, where io is utilized. If BrowserSync updates this module, lite-server will get it. BrowserSync/lite-server currently uses `"socket.io-client": "1.3.7"`: 
https://github.com/BrowserSync/browser-sync/blob/master/package.json#L80

There is a similar request already submitted in BrowserSync's repo: https://github.com/BrowserSync/browser-sync/issues/1026

**Comment by shakyShane** [comment]
Browsersync is now on 1.4.5

**Comment by cgmartin** [comment]
Closing this as "should be supported now" and "not a lite-server issue".
