### ISSUE TITLE
option to start lite server w/o launching browser

### ISSUE THREAD

**Issue by myusrn** [johnpapa/lite-server#48]
is there a switch i'm overlooking that would enable starting lite server w/o launching browser?

the reason for this ask is so that from command line I can launch lite server and then from vscode I can use chrome extension to start and attach to that browser instances pointed at lite server address.

this can be repro'd using https://github.com/myusrn/vscng2qs which is simple https://angular.io/docs/ts/latest/quickstart.html based solution that has package.json configured to allow "npm run lite" from command line to start server, where I don't want it kicking off browser, so I can then move to vscode and use debug | "Launch localhost with sourcemaps" option to kick off instance of chrome pointed at that server.

**Comment by cgmartin** [comment]
https://www.browsersync.io/docs/options/#option-open
```
{ "open": false }
```

**Comment by myusrn** [comment]
that works thanks.
