### ISSUE TITLE
Server-Side rendering support?

### ISSUE THREAD

**Issue by jesussobrino** [johnpapa/lite-server#50]
This could be a stupid question. But I really would like to know if lite-server support Server-side rendering in somehow.

Thanks in advance.

**Comment by cgmartin** [comment]
Highly doubtful. lite-server is a simple static dev server for single-page web applications. 

I'd look into using a node.js web framework designed for server-side rendering: 
https://github.com/sindresorhus/awesome-nodejs#web-frameworks
