### ISSUE TITLE
referencing node_modules outside base path

### ISSUE THREAD

**Issue by madhusudhand** [johnpapa/lite-server#52]
In an angular 2 application with structure as
app
|-- node_modules
|-- src
     |-- index.html

and bs-config as
"server": { "baseDir": "./src" }

How do I reference the angular sources in my index.html which are outside my base path.
If i give base path as "/", then I have to invoke the url with /src/index.html always.

**Comment by cgmartin** [comment]
Try multiple base directories:
(via <https://www.browsersync.io/docs/options/#option-server>)
```
// Multiple base directories
server: {
    baseDir: ["src", "node_modules"]
}
```

**Comment by woleicom** [comment]
dir:
app
|-- node_modules
|-- angular2
------|-- system
------------|-- index.html

index.html:
```
<script src="../../node_modules/core-js/client/shim.min.js"></script>
<script src="../../node_modules/zone.js/dist/zone.js"></script>
<script src="../../node_modules/reflect-metadata/Reflect.js"></script>
<script src="../../node_modules/systemjs/dist/system.src.js"></script>
```
bs-config.js:
```
{
  "port": 8989,
  "server": { "baseDir": ["angular2/system","node_modules"]}
}
```
error:
```
[BS] Watching files...
16.07.20 09:04:31 304 GET /index.html
16.07.20 09:04:35 304 GET /styles.css
16.07.20 09:04:35 304 GET /systemjs.config.js
16.07.20 09:04:35 404 GET /node_modules/core-js/client/shim.min.js
16.07.20 09:04:35 404 GET /node_modules/zone.js/dist/zone.js
16.07.20 09:04:35 404 GET /node_modules/reflect-metadata/Reflect.js
16.07.20 09:04:35 404 GET /node_modules/systemjs/dist/system.src.js
```
BaseDir add more or less, I would like to ask how to configure？

**Comment by emramos** [comment]
I've just faced a similar issue.
If you include "node_modules" as part of baseDir, it becomes part of the root structure. All files inside node_modules will become directly available to the rest of the application.

Therefore, you should not reference it anymore:
```html
<script src="core-js/client/shim.min.js"></script>
<script src="zone.js/dist/zone.js"></script>
<script src="reflect-metadata/Reflect.js"></script>
<script src="systemjs/dist/system.src.js"></script>
```

If you want to keep referencing node_modules inside your index.html, a better approach is to add a route in your bs-config.js:

```json
{
  "server": { "baseDir": "angular2/system"},
   "routes" : { "/node_modules" : "./node_modules"}
 }
```
