### ISSUE TITLE
lite-server folder structure causing file path length issues

### ISSUE THREAD

**Issue by JerryLan01** [johnpapa/lite-server#58]
Using the current Angular2 Quickstart for Typescript
https://github.com/angular/quickstart/blob/master/README.md
It is difficult to create a fully installed node_modules with npm because within the folder there are several subfolders with path lengths so long that they can not be copied into a Windows 10 folder structure without placing them in a folder with a name of about 6 characters or fewer at the very root of the drive. I discovered this while trying to port the project to Visual Studio 2015.  I noticed that using GIT Bash to perform the NPM Install worked, however the content of the node_modules folder could not be copied after that without errors.
A couple of examples of folders in this category are balanced-match, concat-map and color-convert.

os Windows 10
git version 2.7.4.windows.1
Visual Studio 2015 Update 1
Visual Studio Code

**Comment by johnpapa** [comment]
I understand your frustration, but this is not soemthing lite-server can help with. This is more of using npm and long file paths. Perhaps let the angular team and microsoft windows teams know.
