### ISSUE TITLE
Open the browser page with an alias

### ISSUE THREAD

**Issue by matteosuppo** [johnpapa/lite-server#6]
What if I want to open the browser on "http://my-app:3000" instead of "http://localhost:3000"?

If I have the correct /etc/hosts file it works, but I can't find a way to make the initial open to have the correct name.

It's just a minor issue of personal taste, but I'm curious.

**Comment by vikeen** [comment]
I believe this will browser-sync option solve your problem - https://browsersync.io/docs/options/#option-proxy.

In addition to that with #1. @johnpapa is asking for feedback on how to handle pass through options to browser-sync from as a lite-server user. From my understanding, if the .rc approach pans out then you could just set the proxy config option in the new lite-server rc file configuration. This would then pass your option on to browser-sync and all should be good.

I tried to word this a couple different ways and I think it's still confusing. Does this help?

**Comment by matteosuppo** [comment]
I'll have to try it! Thanks

**Comment by johnpapa** [comment]
Version 2.0 has been published. New API that follows the exact `bs-config.js` format for all overrides.
