### ISSUE TITLE
Rename lite-server to identify it as a quick, easy, simple, demo server not for production use

### ISSUE THREAD

**Issue by johnpapa** [johnpapa/lite-server#66]
There has been confusion on the purpose of lite-server. We get asked about using lite-server with IIS, using it to be a full fledged production server, how to deploy it. lite-server is intended to be a server for:

1. demo use
2. quick and easy server without having to write any server code
3. help you focus on writing client code 

It is not intended for anything beyond this.

Perhaps we should rename it to `demo-server` ?

**Comment by peterjhart** [comment]
I don't think you need to cater to developers that don't read.

**Comment by cgmartin** [comment]
`demo-spa-server`? 

Since this is already published as `lite-server`, I have worry about the confusion renaming may cause for existing users, and changes to existing commands `ie. npm run lite`.

**Comment by johnpapa** [comment]
I agree ... i opened this issue partially to remind myself to make it even clearer in the README file and partially to make it more discoverable that this is not a production server :)

**Comment by kylecordes** [comment]
Ideas:

* lite-dev-server
* spa-dev-server
* development-web-server
* browser-sync-server
* papa-server (my favorite...)

**Comment by johnpapa** [comment]
going to close this as the name has been fine
