### ISSUE TITLE
BrowserSync v2.12.4 breaks default file watching

### ISSUE THREAD

**Issue by garkbit** [johnpapa/lite-server#74]
As stated in the title, BS 2.12.4 breaks default file watching behavior. It changes how the `files` input array is processed. I've opened an [issue on the BS repo](https://github.com/BrowserSync/browser-sync/issues/1080), but it may be worth considering updating the default `files` array, depending upon how they choose to handle the issue.

### Bug repro steps

1. Make sure your package is using BrowserSync v2.12.4
2. Use the default `files` option (`files: ['./**/*.{html,js,css}']`, I believe) 
3. Run lite-server
4. Modify a file that should trigger a reload
5. No reload

### Environment
- `lite-server` version: 2.2.0
- `nodejs` version: 5.3.0
- `npm` version: 3.8.1
- OS type/version: OSX

**Comment by shakyShane** [comment]
This is resolved in v2.12.5, sorry for any inconvenience caused :)
