### ISSUE TITLE
Turning off root fallbacks?

### ISSUE THREAD

**Issue by amellnik** [johnpapa/lite-server#76]
I didn't see any issues about this either here or at BrowserSync, and while it might be slightly out of the intended scope of lite-server, I was wondering if there's an easy way to do this.  

If I have a directory structure like 

```
index.html
/blah/index.html
```

requests to `/blah` and `/whatever` both fall back to the root `index.html`.  Is there a way to only fall back to the root one if there's not a matching path with a `index.html`?

**Comment by ascarff** [comment]
+1
