### ISSUE TITLE
Command line arguments no longer supported?

### ISSUE THREAD

**Issue by lordmat0** [johnpapa/lite-server#80]
Hi there,

Are the command line arguments no longer supported? They use to work but are now ignored. I did notice no mention of them in the documentation.

From bash:
```
> lite-server  --files target/ui/**/*.html target/ui/**/*.js --baseDir target/ui

Did not detect a `bs-config.json` or `bs-config.js` override file. Using lite-server defaults...
** browser-sync config **
{ injectChanges: false,
  files: [ './**/*.{html,htm,css,js}' ],
  watchOptions: { ignored: 'node_modules' },
  server: { baseDir: './', middleware: [ [Function], [Function] ] } }
```

Not sure if this is an issue with this project or browsersync

lite-server 2.2.0
nodejs 4.4.5
OSX

Thanks,
Mat

**Comment by johnpapa** [comment]
we use browser-sync under the covers and instead of exposing all options of our own accord, we use the bs-config file. this change was part of an overhaul for v2.
