### ISSUE TITLE
Lite server not working

### ISSUE THREAD

**Issue by debapamdas** [johnpapa/lite-server#86]
i installed lite-server as the only dependency in my project and tried run it but it is failing. The error displayed in the npm debug log is

0 info it worked if it ends with ok
1 verbose cli [ 'C:\Program Files\nodejs\node.exe',
1 verbose cli   'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@3.9.3
3 info using node@v6.2.1
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle lite@1.0.0~predev: lite@1.0.0
6 silly lifecycle lite@1.0.0~predev: no script for predev, continuing
7 info lifecycle lite@1.0.0~dev: lite@1.0.0
8 verbose lifecycle lite@1.0.0~dev: unsafe-perm in lifecycle true
9 verbose lifecycle lite@1.0.0~dev: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users****_\Desktop\lite\node_modules.bin;C:\Program Files\nodejs; C:\Program Files\nodejs\;C:\Program Files\nodejs\;C:\ProgramData\Oracle\Java\javapath;C:\oracle\product\11.2.0\client32;C:\oracle;C:\Program Files\Citrix\System32\;C:\Program Files\Citrix\ICAService\;C:\Program Files (x86)\Common Files\Citrix\System32\;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Users\**_**_\AppData\Local\Programs\Git\cmd;C:\Users\**_**_\AppData\Roaming\npm
10 verbose lifecycle lite@1.0.0~dev: CWD: C:\Users\**_**_\Desktop\lite
11 silly lifecycle lite@1.0.0~dev: Args: [ '/d /s /c', 'lite-server' ]
12 silly lifecycle lite@1.0.0~dev: Returned: code: 1  signal: null
13 info lifecycle lite@1.0.0~dev: Failed to exec dev script
14 verbose stack Error: lite@1.0.0 dev: `lite-server`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:245:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:852:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid lite@1.0.0
16 verbose cwd C:\Users\**_**\Desktop\lite
17 error Windows_NT 6.1.7601
18 error argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "run" "dev"
19 error node v6.2.1
20 error npm  v3.9.3
21 error code ELIFECYCLE
22 error lite@1.0.0 dev: `lite-server`
22 error Exit status 1
23 error Failed at the lite@1.0.0 dev script 'lite-server'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the lite package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     lite-server
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs lite
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls lite
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
### Environment
- `lite-server` version: 2.2.0
- `nodejs` version: 6.2.1
- `npm` version: 3.9.3
- OS type/version: windows 7 64-bit

**Comment by PHBeagle** [comment]
I had to install npm into my project directory ("..\Source\Repos\angular2-get-started") before lite-server would work.  I had previously installed npm/node.js outside of the project directory.  Not sure if this will solve your problem or not, but its something else that you can try as it worked for me.
