### ISSUE TITLE
Override defaults / bs-config via CLI params.

### ISSUE THREAD

**Issue by Foxandxss** [johnpapa/lite-server#87]
So for angular.io we will use lite-server for e2e tests and there are three cases:

Normal e2e tests that runs with this config:

```
module.exports = {
  open: false,
  logLevel: "silent",
  port: 8080,
  server: {
    middleware: {
      0: null
    }
  }
};
```

Then we have e2e for CLI / webpack with this other config:

```
module.exports = {
  open: false,
  logLevel: "silent",
  port: 8080,
  server: {
    baseDir: './dist',
    middleware: {
      0: null
    }
  }
};
```

They are both the same, except the baseDir.

Then dart tests, they are different and we need a dynamic `baseDir` for each one. We run them from different places and the dir will always change.

So would be awesome if we could do something like:

`lite-server --port=8080 --silent --no-open --baseDir=./foo`

But I can also see a simple solution for now:

`lite-server -c /path/to/bs-config.json --baseDir=./foo`

That way we can use just 1 file and be able to test the 3 different solutions.

What do you think?

**Comment by cpamp21** [comment]
+1

**Comment by webia1** [comment]
yes, something like

`lite-server -c port=4200` or `lite-server --port=4200` would be great,..

**Comment by andreasonny83** [comment]
just merged the baseDir implementation in https://github.com/johnpapa/lite-server/pull/115
