### ISSUE TITLE
Trying to run lite-server

### ISSUE THREAD

**Issue by pierpy** [johnpapa/lite-server#9]
I'm a node.js beginner...i'm trying to use lite-server in my app development. 
I downloaded the repository in my app folder and I run lite-server command but nothing happens...can you help me to setup it correctly?

**Comment by johnpapa** [comment]
did you run `npm install lite-server -g` ? do that first then run it for globally using it.

run `npm i lite-server --save-dev` to run it for dev

**Comment by pierpy** [comment]
the first was ok...
but the second give me :
GET https://registry.npmjs.org/lite.server
npm http 404 https://registry.npmjs.org/lite.server
npm ERR! TypeError: Cannot read property 'latest' of undefined
npm ERR!     at next (/usr/share/npm/lib/cache.js:687:35)
npm ERR!     at /usr/share/npm/lib/cache.js:675:5
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-37-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "i" "lite.server" "--save-dev"
npm ERR! cwd /home/pierpaolo
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! type non_object_property_load
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pierpaolo/npm-debug.log
npm ERR! not ok code 0

**Comment by maheshk172** [comment]
I am facing this same issue.  I am trying to run angular2-quickstart tutorial on Linux - Ubuntu 14.4 LTS version.  The server starts properly and browser launch with http://localhost:3000 as well  but then it stops with error.

I am using  "lite-server": "^1.3.2" as mentioned on the tutorial.

Find below error details. 

[BS] Watching files...
15.12.31 17:48:17 304 GET /./index.html (Unknown - 27ms)
15.12.31 17:48:17 304 GET /node_modules/angular2/bundles/angular2.dev.js (Unknown - 23ms)
15.12.31 17:48:17 304 GET /node_modules/es6-shim/es6-shim.js (Unknown - 24ms)
15.12.31 17:48:17 304 GET /node_modules/angular2/bundles/angular2-polyfills.js (Unknown - 14ms)
15.12.31 17:48:17 304 GET /node_modules/systemjs/dist/system.src.js (Unknown - 16ms)
15.12.31 17:48:17 304 GET /node_modules/rxjs/bundles/Rx.js (Unknown - 17ms)
15.12.31 17:48:18 304 GET /app/boot.js (Unknown - 348ms)
15.12.31 17:48:19 304 GET /app/app.component.js (Unknown - 85ms)
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: watch node_modules/lite-server/node_modules/browser-sync/node_modules/serve-index/node_modules/http-errors/node_modules/inherits/test.js ENOSPC
    at exports._errnoException (util.js:870:11)
    at FSWatcher.start (fs.js:1234:19)
    at Object.fs.watch (fs.js:1262:11)
    at createFsWatchInstance (/home/mahesh/workspaces/AngularJS2Study/angular2-quickstart-typescript/node_modules/lite-server/node_modules/browser-sync/node_modules/chokidar/lib/nodefs-handler.js:37:15)

Could you please advise on this.

**Comment by xavierdutreilh** [comment]
@pierpy, are you sure that you typed `lite-server` and not `lite.server`? The following line seems to say the opposite: `npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "i" "lite.server" "--save-dev"`.

@maheshk172, it seems to be an issue with `browser-sync` itself. https://github.com/BrowserSync/browser-sync/issues/224 provides some answer on how to fix it.

**Comment by johnpapa** [comment]
If on Ubuntu, running the following command might solve the problem: 
echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

Reference:
http://stackoverflow.com/questions/16748737/grunt-watch-error-waiting-fatal-error-watch-enospc

**Comment by ReneVallecillo** [comment]
@johnpapa works on ElementaryOS

**Comment by AdrianZelada** [comment]
very good @johnpapa thanks....

**Comment by msushil** [comment]
i've included bs-config.json and it works for me.

**Comment by cbolivar-sts** [comment]
Hello John,

I am using the lite-server with AngularJS 2, but I have problem because when I try to get css files, the browser can't found it.

My folder structure is:

-- WebUI [root]
----- app (js,ts,map files)
----- css (css files to main page)
----- node_moudles
----- typings
-- index.html

That is my bs-config.json file:
```
{
  "port": 8000,
}
```

index.html has the following references:
```
 <!-- >> Custom Styles to Application [CSS] << -->
    <link href="css/app-custom-member-styles.css" rel="stylesheet"/>
    <link href="css/responsive-app.css" rel="stylesheet" />
```


But when I run, the browser can't find the css these files.

How can I do to lite server take internal folders (as work IIS)?

Thank you!

**Comment by gupta1pooja** [comment]
cbolivar-sts - Did you find the solution to your issue?

**Comment by gupta1pooja** [comment]
Hey cbolivar-sts, Did you find the solution to this issue?

**Comment by georanma** [comment]
this worked for me @johnpapa. Thanks. 

Very weird though that my set up was working, and then just kind of stopped. Not sure what changed during the course of the tutorial class Im working on.

**Comment by MacgyverMartins** [comment]
For anyone that comes here to finding a solution to `command not found: lite-server` error
here is a solution:

if you installed by running `npm i lite-server --save-dev`
you should add this command on your package.json
for example: "dev": "lite-server". And then run `npm run dev`

But if you instal using `npm i lite-server -g`, then you would be able to run` lite-server` from your terminal

**Comment by ShivamChawla01** [comment]
I am also facing same issue with **npm install lite-server --save-dev** .
It starts installing but after a while it gets stuck at Fetchmetadata: sill resolveUsingNewModule.

**Comment by pazcur** [comment]
> did you run `npm install lite-server -g` ? do that first then run it for globally using it.
> 
> run `npm i lite-server --save-dev` to run it for dev

Thank you @johnpapa that totally fixed my issue. For reference here's the error message that I got.
![image](https://user-images.githubusercontent.com/25714627/45835094-13bdda80-bcd7-11e8-91b8-de9ea5e6fd26.png)

**Comment by Mtea994** [comment]
i am facing this issue while using terminal on vs code using windows OS
```
lite-server : The term 'lite-server' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name,
or if a path was included, verify that the path is correct and try again.

```

**Comment by kamalraj21** [comment]
> did you run `npm install lite-server -g` ? do that first then run it for globally using it.
> 
> run `npm i lite-server --save-dev` to run it for dev

Worked for me as well, Thank you!

**Comment by ShivamChawla01** [comment]
got it resolved somehow...I don't remember though

**Comment by Jayanth312** [comment]
:\git-test>npm start
npm ERR! missing script: start

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jkcho\AppData\Roaming\npm-cache\_logs\2020-04-18T13_48_56_816Z-debug.log

D:\git-test>
I am getting this kind of error

**Comment by pranita24sahay** [comment]
![help](https://user-images.githubusercontent.com/51882720/82187171-a201be00-9909-11ea-8486-d3a5b4699094.PNG)

**Comment by ghazaljangid** [comment]
> did you run `npm install lite-server -g` ? do that first then run it for globally using it.
> 
> run `npm i lite-server --save-dev` to run it for dev

thanks @johnpapa it totally worked!

**Comment by GangaPradeep** [comment]
Hey @pranita24sahay  I am also facing the same problem while installing the live-server package using npm ]. Have you find a solution for you problem. If you found the solution please share the solution......
