### ISSUE TITLE
File changes don't trigger browser reload

### ISSUE THREAD

**Issue by maciej-gurban** [johnpapa/lite-server#99]
### Description

The server recognizes changes to files in the root directory and reloads the browser when using default configuration (no bs-config.js) just fine. The problem appears when defining a custom project directory and reflecting that in the config file.

The config seems to get applied correctly since specifying additional options (like "https": true) does establish the server via https, and files from custom directory do get served correctly.

### To reproduce

Directory structure:
```
dist
-- index.html
package.json
bs-config.json
```

File bs-config.json
```
{
    "files" : "./dist/**/*.{js, html, css}",
    "server" : { "baseDir" : "./dist" },
    "browser" : ["google-chrome"]
}
```

Running lite-server (via npm scripts) does conjure up a browser at port 3000, and serves the files, but changes to these files will not cause the browser to refresh nor load the changes.

### Environment
- `lite-server` version: 2.2.2
- `nodejs` version: 5.8.0
- `npm` version: 3.7.3
- OS type/version: OSX 10.11.5

**Comment by maciej-gurban** [comment]
Upon further investigation (and reading the source code), it looks like either Browserify pattern matching might be the culprit, or some simple mistake I'm making. I replaced bs-config.json with the following and everything works:

```
{
    "files" : [
      "./**/*.html",
      "./**/*.css",
      "./**/*.js"
    ],
    "server" : { "baseDir" : "./dist" },
    "browser" : ["google-chrome"]
}
```

**Comment by ShashankaNataraj** [comment]
@maciej-gurban I have this exact same issue, but without the bs-config.json. The readme says bs-config.json is optional, I don't have a bs-config file, and live reload doesn't work!

**Comment by ShashankaNataraj** [comment]
My bad, my html code skeleton wasnt in place and I was just trying to get this working, didnt realize browser sync depends on injecting scripts... Fixed the skeleton HTML code and browsersync works as expected! Thanks!

**Comment by blachawk** [comment]
@maciej-gurban maciej-gurban thanks for finding the fix.  Your layout of a bs-config.json has helped me in regards to the issue.  I wonder what the main difference is between what you did and what original tutorials are showing in regards to a bs-config.json file.  But in either case, I'm happy that the live reload is back!  

I wish there was a way to set a custom home page (i.e. index.1.htm) within the bs-config file, but thats another story.

Thanks again

**Comment by maciej-gurban** [comment]
@blachawk I haven't tried myself, but browsing through [browsersync reference](https://browsersync.io/docs/options/) it should be possible to do:
```
server: {
    baseDir: "app",
    index: "index.htm"
}
```

Either that, or even going with manually importing the fallback and configuring it, as the [source code](https://github.com/johnpapa/lite-server/blob/master/lib/config-defaults.js#L18) does it. You'd need to install `connect-history-api-fallback` to use it in server configuration and change bs-config to be a JS file.

**Comment by Orodan** [comment]
Hi,

I have a similar problem with lite-server, it does not detect my file changes.
I've tried with and without an bs-config file, and I can't get it to work.

Here is some informations about my system :
- os : macOS Sierra 10.12.6
- lite-server : 2.3.0
- node : 8.9.4
- npm : 5.6.0

I installed lite-server globally and did not have any problems. That's the first time I tried lite-server on this machine. I'll appreciate if someone can help, let me know if you need any more info :)

**Comment by charan5181** [comment]
Auto reloading of Browser using browser-sync:
npm i -g browser-sync
Since you are already using Node.JS server, you can use proxy by editing property in  package.json as given below under scripts:
Note:Port i am using in my local host is 5000
  {
  "name": "express-demo",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "browser-sync-proxy": "browser-sync start --proxy localhost:5000 serveStatic ../frontend --files ../frontend"
  }

  
My Path  where my front end files resides is: "../frontend"
After Changing the above file just open another cmd prompt, change dir to your project folder and use : npm run browser-sync-proxy.

Now whatever changes you make and save in your frontend files,No need to reload Browser.
Changes will be reflected. Voila....

**Comment by ashishepost** [comment]
I think all above responses are OK but default configuration for **lite-server** will watch for all files & must work without even _bs-config.json_ file.

The working solution for this issue is with root [index.html] file.

please make sure that your *.html file must have proper HTML Root tags for example:

Working _index.html_ basic contents

<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>Page Title</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>    
    <script src='any-script.js'></script>
</head>
<body>
    
</body>
</html>

**Comment by andb0t** [comment]
Your link to "pen" doesn't work anymore, but here's what fixed my "problem". Contenf of my `index.html` in the root directory:
```
<!DOCTYPE HTML>
<html>
  <head>
  	<title>My test page</title>
  </head>
  <body>
    <h1>My test page</h1>
    <h2>It works now</h2>
    <p>with autoreload!</p>
  </body>
</html>
```
